project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - public-summary.qmd
    - clam-dashboard.qmd
    - reporting-summary.md
    - figures/resazurin-applications-diagram.md

website:
  # Omitting the title will hide it
  navbar:
    left:
      - text: "Technical Documentation"
        file: index.qmd
      - text: "Clam Dashboard"
        file: clam-dashboard.qmd
      - text: "Public Summary"
        file: public-summary.qmd
    right:
      - icon: github
        href: https://github.com/RobertsLab/resazurin-assay-development
        aria-label: GitHub
      - icon: envelope-paper
        file: https://faculty.washington.edu/sr320/contact.html  

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toggle: true